server:
  port: 8085
eureka:
  client:
    serviceUrl:
<<<<<<< Updated upstream
      defaultZone: http://localhost:8091/eureka
=======
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
>>>>>>> Stashed changes
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
<<<<<<< Updated upstream
            - Path=/category/**, /producto/**
          filters:
            - AuthFilter
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**
          filters:
            - AuthFilter
        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/order/**
=======
            - Path=/category/**
>>>>>>> Stashed changes
          filters:
            - AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
